Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Exam.Models;

namespace Exam.Controllers
{
    public class ActivityController : Controller
    {
        private MyContext _DB;
        // here we can "inject" our context service into the constructor
        public ActivityController(MyContext context)
        {
            _DB = context;
        }

        [HttpGet("dashboard")]
        public IActionResult Dashboard()
        {
            int? uid = HttpContext.Session.GetInt32("User_Id");
            if(uid == null){
                return RedirectToAction("Index", "Home");
            }
            List<ActivityT> allActivities = _DB.Activities
                .Include(a => a.Coordinator)
                .Include(a => a.Attends)
                .OrderByDescending(a => a.CreatedAt)
                .ToList();

            foreach (var activity in allActivities){
                if(activity.ActivityDate < DateTime.Now){
                // Remove it
                    return Redirect($"delete/{activity.ActivityId}");
                }
            }
            User u = _DB.Users.FirstOrDefault(u => u.UserId == (int)uid);
            ViewBag.User = u;
            return View(allActivities);
        }

        [HttpGet("new")]
        public IActionResult NewActivity()
        {
            int? uid = HttpContext.Session.GetInt32("User_Id");
            User u = _DB.Users.FirstOrDefault(u => u.UserId == (int)uid);
            ViewBag.User = u;
            return View();
        }

        [HttpPost("add")]
        public IActionResult Add(ActivityT A)
        {
            // if (A.ActivityDate < DateTime.Now)
            // {
            //     ModelState.AddModelError("ActivityDate", "Activity Date must be in the Future!");
            // }
            int? uid = HttpContext.Session.GetInt32("User_Id");
            if (ModelState.IsValid)
            {
                A.UserId = (int)uid;
                _DB.Activities.Add(A);
                _DB.SaveChanges();
                return Redirect($"activity/{A.ActivityId}");
            }

            User u = _DB.Users.FirstOrDefault(u => u.UserId == (int)uid);
            ViewBag.User = u;
            return View("NewActivity");
        }

        [HttpGet("activity/{ActivityId}")]
        public IActionResult OneActivity(int ActivityId)
        {
            int? uid = HttpContext.Session.GetInt32("User_Id");
            ActivityT oneActivity = _DB
            .Activities
            .Include(a => a.Coordinator)
            .Include(a => a.Attends)
            .ThenInclude(j => j.user)
            .FirstOrDefault(a => a.ActivityId == ActivityId);

            Console.WriteLine("oneActivity.Coordinator.FirstName");
            Console.WriteLine(oneActivity.Coordinator);

            User u = _DB.Users.FirstOrDefault(u => u.UserId == (int)uid);
            ViewBag.User = u;
            return View(oneActivity);
        }
        [HttpGet("join/{ActivityId}")]
        public IActionResult Join(int ActivityId)
        {
            int? uid = HttpContext.Session.GetInt32("User_Id");
            ActivityT A = _DB.Activities.FirstOrDefault(a => a.ActivityId == ActivityId);
            //     foreach (var date in A.Attends){
            //         foreach (var userdates in date.user.Joins){
            //             if(A.ActivityDate == userdates.Activity.ActivityDate){
            //                 Console.WriteLine("Cannot");
            //                 return RedirectToAction("Dashboard");
            //             }
            //      }
            // }
            Join join = new Join();
            join.UserId = (int)uid;
            join.ActivityId = ActivityId;
            _DB.Joins.Add(join);
            _DB.SaveChanges();
            return RedirectToAction("Dashboard");
        }

        [HttpGet("leave/{ActivityId}")]
        public IActionResult Leave(int ActivityId)
        {
            int? uid = HttpContext.Session.GetInt32("User_Id");
            Join leave = _DB.Joins.FirstOrDefault(l => l.ActivityId == ActivityId && l.UserId == (int)uid);
            _DB.Joins.Remove(leave);
            _DB.SaveChanges();
            return RedirectToAction("Dashboard");
        }

        [HttpGet("delete/{ActivityId}")]  // movieId has to match the asp-route-movieId
        public IActionResult Delete(int ActivityId)
        {
            int? uid = HttpContext.Session.GetInt32("User_Id");
            if(uid == null){
                return RedirectToAction("Index", "Home");
            }
            ActivityT act = _DB.Activities.FirstOrDefault(a => a.ActivityId == ActivityId);
            _DB.Activities.Remove(act);
            _DB.SaveChanges();
            return RedirectToAction("Dashboard");
        }
    }
}

Views/Activity/Dashboard.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model List<ActivityT>
<div class="text-center">
    <h2>Dojo Activity Center <h5>Welcome, @ViewBag.user.FirstName! <a asp-action="Logout" asp-controller="Home">Logout</a> </h5> </h2> 
    <br>
    <table class="table table-striped table-light">
        <thead>
            <th>Activity</th>
            <th>Date and Time</th>
            <th>Duration</th>
            <th>Event Coordinator</th>
            <th>No. of Participations</th>
            <th>Actions</th>
        </thead>
        @foreach (var act in Model){
            <tr>
                @* <td> <a asp-action="Weddings" asp-controller="Wedding" asp-route-Wedding_Id="@wedding.Wedding_Id">@wedding.WedderOne & @wedding.WedderTwo</a> </td> *@
                <td> <a asp-action="OneActivity" asp-controller="Activity" asp-route-ActivityId="@act.ActivityId">@act.Title</a> </td>
                <td> @act.ActivityDate.ToString("d") At @act.ActivityTime @act.Time </td>
                <td> @act.ActivityDuration @act.Duration  </td>
                <td> @act.Coordinator.FirstName @act.Coordinator.LastName </td>
                <td> @act.Attends.Count </td>
                <td>
                    @if (act.UserId == ViewBag.user.UserId)
                    {
                        <a asp-action="Delete" asp-controller="Activity" asp-route-ActivityId="@act.ActivityId"><button
                        class="btn btn-sm btn-danger">Delete</button></a>
                    }
                    else if (@act.Attends.Any(f => f.UserId == ViewBag.User.UserId))
                    {
                        <a asp-action="Leave" asp-controller="Activity" asp-route-ActivityId="@act.ActivityId"><button
                            class="btn btn-sm btn-warning">Leave</button></a>
                    }
                    else
                    {
                        @* @foreach (var activity in Model){
                            @foreach (var date in activity.Attends){
                                if(activity.ActivityDate == date.Activity.ActivityDate){
                                    <script>alert("You cannot join 2 activities at Same time!");</script>
                                }
                            }
                        } *@
                        <a asp-action="Join" asp-controller="Activity" asp-route-ActivityId="@act.ActivityId"><button
                            class="btn btn-sm btn-primary">Join</button></a>
                    }
                </td>
            </tr>
        }
    </table>
    <a asp-action="NewActivity" asp-controller="Activity"><button class="btn btn-sm btn-primary">Add New Activity</button></a>
</div>


Views/Activity/NewActivity.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model ActivityT
<div class="text-center">
    <h2>Dojo Activity Center <h5><a asp-action="Logout" asp-controller="Home">Logout</a> <a asp-action="Dashboard" asp-controller="Activity">Home</a></h5> </h2> 
    <h4>Create An Activity</h4>
    <br>
    <form asp-action="Add" asp-controller="Activity" method="POST">
        <div>
            <label asp-for="Title"></label>
            <input asp-for="Title" /><br />
            <span style="color: red; font-size: 8pt;" asp-validation-for="Title"></span>
        </div>
        <div>
            <label asp-for="ActivityDate"></label>
            <input asp-for="ActivityDate" /><br />
            <span style="color: red; font-size: 8pt;" asp-validation-for="ActivityDate"></span>
        </div>
        <div>
            <label asp-for="ActivityTime"></label>
            <input asp-for="ActivityTime" />
            <select asp-for="Time">
                <option>A.M.</option>
                <option>P.M.</option>
            </select><br />
            <span style="color: red; font-size: 8pt;" asp-validation-for="ActivityTime"></span>
        </div>
        <div>
            <label asp-for="ActivityDuration"></label>
            <input asp-for="ActivityDuration" />
            <select asp-for="Duration">
                <option>Minutes</option>
                <option>Hours</option>
                <option>Days</option>
            </select><br />
            <span style="color: red; font-size: 8pt;" asp-validation-for="ActivityDuration"></span>
        </div>
        <div>
            <label asp-for="Description" style="vertical-align: top;"></label>
            <textarea asp-for="Description"></textarea><br />
            <span style="color: red; font-size: 8pt;" asp-validation-for="Description"></span>
        </div>
        <button type="submit">Create Activity</button>
    </form>
</div>

Views/Activity/OneActivity.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model ActivityT
<div class="">
    <h2>Dojo Activity Center <h5> <a asp-action="Logout" asp-controller="Home">Logout</a> <a asp-action="Dashboard" asp-controller="Activity">Home</a></h5> </h2> 
    <h3>@Model.Title</h3>
    <p>Event Coordinator: @Model.Coordinator.FirstName</p>
    <p>Description: @Model.Description</p>
    <p>Participants: </p>
    <ul>
        @{
            foreach (var attend in Model.Attends)
                {
                    <li>@attend.user.FirstName @attend.user.LastName</li>
                }
        }
    </ul>
    @if (Model.Coordinator.UserId == ViewBag.user.UserId)
                    {
                        <a asp-action="Delete" asp-controller="Activity" asp-route-ActivityId="@Model.ActivityId"><button
                        class="btn btn-sm btn-danger">Delete</button></a>
                    }
                    else if (@Model.Attends.Any(f => f.UserId == ViewBag.User.UserId))
                    {
                        <a asp-action="Leave" asp-controller="Activity" asp-route-ActivityId="@Model.ActivityId"><button
                            class="btn btn-sm btn-warning">Leave</button></a>
                    }
                    else
                    {
                        <a asp-action="Join" asp-controller="Activity" asp-route-ActivityId="@Model.ActivityId"><button
                            class="btn btn-sm btn-primary">Join</button></a>
                    }
</div>